/*
 *running:0,//green
 *stop:1,//原来的眼色 
 *alter:2,//red
 *wait:3,//yellow
 * */
var imgUrlMap = {
	Faunc001:{
		x:"-35",
		y:"-30", 
		stop:"/themes/tdds/images/1-1.png",
		alter:"/themes/tdds/images/1-1-1.png",
		running:"/themes/tdds/images/1-1-2.png",
		wait:"/themes/tdds/images/1-1-3.png"
	},
	Faunc002:{
		x:"3", 
		y:"-30", 
		stop:"/themes/tdds/images/1-2.png",
		alter:"/themes/tdds/images/1-2-1.png",  
		running:"/themes/tdds/images/1-2-2.png",
		wait:"/themes/tdds/images/1-2-3.png"
	},
	Faunc003:{
		x:"42",
		y:"-30",
		stop:"/themes/tdds/images/1-3.png",
		alter:"/themes/tdds/images/1-3-1.png",
		running:"/themes/tdds/images/1-3-2.png",
		wait:"/themes/tdds/images/1-3-3.png"
	},
	Faunc004:{
		x:"81",
		y:"-30",
		stop:"/themes/tdds/images/1-4.png",
		alter:"/themes/tdds/images/1-4-1.png",
		running:"/themes/tdds/images/1-4-2.png",
		wait:"/themes/tdds/images/1-4-3.png"
	},
	m5:{
		x:"11", 
		y:"-23",
		stop:"/themes/tdds/images/1-5.png",
		alter:"/themes/tdds/images/1-5-1.png",
		running:"/themes/tdds/images/1-5-2.png",
		wait:"/themes/tdds/images/1-5-3.png"
	},
	Faunc005:{
		x:"21", 
		y:"-23",
		stop:"/themes/tdds/images/1-6.png",
		alter:"/themes/tdds/images/1-6-1.png",
		running:"/themes/tdds/images/1-6-2.png",
		wait:"/themes/tdds/images/1-6-3.png"
	},
	Faunc006:{
		x:"26",
		y:"-24",
		stop:"/themes/tdds/images/1-7.png",
		alter:"/themes/tdds/images/1-7-1.png",
		running:"/themes/tdds/images/1-7-2.png",
		wait:"/themes/tdds/images/1-7-3.png"
	},
	Faunc007:{
		x:"-47",
		y:"-24",
		stop:"/themes/tdds/images/1-8.png",
		alter:"/themes/tdds/images/1-8-1.png",
		running:"/themes/tdds/images/1-8-2.png",
		wait:"/themes/tdds/images/1-8-3.png"
	},
	Faunc008:{
		x:"-47",
		y:"-24",
		stop:"/themes/tdds/images/1-9.png",
		alter:"/themes/tdds/images/1-9-1.png",
		running:"/themes/tdds/images/1-9-2.png",
		wait:"/themes/tdds/images/1-9-3.png"
	},
	m141:{
		x:"-18", 
		y:"-25",
		stop:"/themes/tdds/images/2-1.png",
		alter:"/themes/tdds/images/2-1-1.png",
		running:"/themes/tdds/images/2-1-2.png",
		wait:"/themes/tdds/images/2-1-3.png"
	},
	m142:{
		x:"16",
		y:"-23",
		stop:"/themes/tdds/images/2-2.png",
		alter:"/themes/tdds/images/2-2-1.png",
		running:"/themes/tdds/images/2-2-2.png",
		wait:"/themes/tdds/images/2-2-3.png"
	},
	m140:{
		x:"-1",
		y:"-23",
		stop:"/themes/tdds/images/2-3.png",
		alter:"/themes/tdds/images/2-3-1.png",
		running:"/themes/tdds/images/2-3-2.png",
		wait:"/themes/tdds/images/2-3-3.png"
	},
	m13:{
		x:"25",
		y:"-41",
		stop:"/themes/tdds/images/3-1.png",
		alter:"/themes/tdds/images/3-1-1.png", 
		running:"/themes/tdds/images/3-1-2.png",
		wait:"/themes/tdds/images/3-1-3.png"
	},
	m190:{
		x:"14",
		y:"-41", 
		stop:"/themes/tdds/images/3-2.png",
		alter:"/themes/tdds/images/3-2-1.png",
		running:"/themes/tdds/images/3-2-2.png",
		wait:"/themes/tdds/images/3-2-3.png"
	},
	m15:{
		x:"18",
		y:"-32",
		stop:"/themes/tdds/images/3-3.png",
		alter:"/themes/tdds/images/3-3-1.png",
		running:"/themes/tdds/images/3-3-2.png",
		wait:"/themes/tdds/images/3-3-3.png"
	},
	m16:{
		x:"23",
		y:"-68", 
		stop:"/themes/tdds/images/4-1.png",
		alter:"/themes/tdds/images/4-1-1.png", 
		running:"/themes/tdds/images/4-1-2.png",
		wait:"/themes/tdds/images/4-1-3.png"
	},
	m17:{
		x:"85",
		y:"-68",
		stop:"/themes/tdds/images/4-1.png",
		alter:"/themes/tdds/images/4-1-1.png",
		running:"/themes/tdds/images/4-1-2.png",
		wait:"/themes/tdds/images/4-1-3.png"
	},
	m18:{
		x:"153",
		y:"-68",
		stop:"/themes/tdds/images/4-1.png",
		alter:"/themes/tdds/images/4-1-1.png",
		running:"/themes/tdds/images/4-1-2.png",
		wait:"/themes/tdds/images/4-1-3.png"
	},
	m202:{
		x:"36", 
		y:"-57",
		stop:"/themes/tdds/images/4-4.png",
		alter:"/themes/tdds/images/4-4-1.png",
		running:"/themes/tdds/images/4-4-2.png",
		wait:"/themes/tdds/images/4-4-3.png"
	},
	m203:{
		x:"36",
		y:"-57",
		stop:"/themes/tdds/images/4-5.png",
		alter:"/themes/tdds/images/4-5-1.png",
		running:"/themes/tdds/images/4-5-2.png",
		wait:"/themes/tdds/images/4-5-3.png"
	},
	m21:{
		x:"22",
		y:"-65",
		stop:"/themes/tdds/images/4-6.png",
		alter:"/themes/tdds/images/4-6-1.png",
		running:"/themes/tdds/images/4-6-2.png",
		wait:"/themes/tdds/images/4-6-3.png"
	},
	m170:{
		x:"17",
		y:"-65",
		stop:"/themes/tdds/images/4-7.png",
		alter:"/themes/tdds/images/4-7-1.png",
		running:"/themes/tdds/images/4-7-2.png",
		wait:"/themes/tdds/images/4-7-3.png"
	},
	m171:{
		x:"4",
		y:"-65",
		stop:"/themes/tdds/images/4-8.png",
		alter:"/themes/tdds/images/4-8-1.png",
		running:"/themes/tdds/images/4-8-2.png",
		wait:"/themes/tdds/images/4-8-3.png"
	},
	m24:{
		x:"76",
		y:"-25",
		stop:"/themes/tdds/images/5-1.png",
		alter:"/themes/tdds/images/5-1-1.png",
		running:"/themes/tdds/images/5-1-2.png",
		wait:"/themes/tdds/images/5-1-3.png"
	},
	m200:{
		x:"10",
		y:"13",
		stop:"/themes/tdds/images/6-1.png",
		alter:"/themes/tdds/images/6-1-1.png",
		running:"/themes/tdds/images/6-1-2.png",
		wait:"/themes/tdds/images/6-1-3.png"
	},
	m201:{
		x:"20",
		y:"13",
		stop:"/themes/tdds/images/6-2.png",
		alter:"/themes/tdds/images/6-2-1.png",
		running:"/themes/tdds/images/6-2-2.png",
		wait:"/themes/tdds/images/6-2-3.png"
	}
}



